/**This file/class contains the process of sending a file over the
 * network by TCP. It reads the data from the file into a byte array
 * and writes it out to the receiver.  The code generated by the Netbeans
 * IDE which handles the GUI is also present in this class. This class 
 * also contains the code, that had to be manually implemented, which
 * handles the operations that occur upon clicking the button on the GUI.
 * 
 * @author Keagan Selwyn Gill
 **/

import java.io.BufferedInputStream;
import java.io.DataOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.OutputStream;
import java.net.ServerSocket;
import java.net.Socket;
import javax.swing.JFileChooser;

/**
 *
 * @author Keagan
 */
public class TCPSenderWindow extends javax.swing.JFrame {

    File file = null;
    String fileName;
    static Socket socket = null;
    static OutputStream os = null;
    static DataOutputStream dos = null;
    /**
     * Creates new form TCPSenderWindow
     */
    public TCPSenderWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        chooseFileButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("TCP Sender");

        chooseFileButton.setText("Select File");
        chooseFileButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                chooseFileButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(180, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(179, 179, 179))
            .addGroup(layout.createSequentialGroup()
                .addGap(200, 200, 200)
                .addComponent(chooseFileButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(46, 46, 46)
                .addComponent(chooseFileButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(80, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /** This method executes when the user clicks the select file button.
     * It lets the user select a file and then proceeds to execute the
     * instructions to send the file via TCP.
     **/
    private void chooseFileButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chooseFileButtonMouseClicked
        JFileChooser jfc = new JFileChooser(); // File browser to choose file
        jfc.setFileSelectionMode(JFileChooser.FILES_ONLY); // Only files can be chosen (not directories)
        if (jfc.isMultiSelectionEnabled()) { // Only one file at a time (no multiple selection)
            jfc.setMultiSelectionEnabled(false);
        }

        int r = jfc.showOpenDialog(null);
        
        System.out.println("Ready to send file once file has been selected.");
        if (r == JFileChooser.APPROVE_OPTION) {
            try {
                // Store file and the file name in variables 
                file = jfc.getSelectedFile();
                fileName = file.getName();
                // Transfer the file name
                dos.writeUTF(fileName);
                // Create a buffered file input stream for reading the file
                // into a byte array
                FileInputStream fis = new FileInputStream(file);
                BufferedInputStream bis = new BufferedInputStream(fis);
                // Initialize the byte array that will get the file's data
                // read into
                byte[] contents;
                // Store the file size into a variable and transfer the
                // file size value to the receiver
                long fileSize = file.length();
                dos.writeLong(fileSize);
                
                // This is the algorithm that sends the file to the receiver
                // via TCP. It does so in seperate chunks of the file. It also
                // computes the progress of transfer and prints it to the 
                // terminal.
                long current = 0;
                while(current!=fileSize){
                    int size = 10000;
                    if(fileSize - current >= size) {         
                        current += size;                 
                    } else {                  
                        size = (int)(fileSize - current);
                        current = fileSize;
                    }                  
                    contents = new byte[size];    
                    bis.read(contents, 0, size);           
                    os.write(contents);
                    int progress = (int)((current*100)/fileSize);
                    System.out.println("Sending file ... "+progress+"% complete!");
                }
                os.flush();    
                System.out.println("File sent succesfully!");
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
        
    }//GEN-LAST:event_chooseFileButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TCPSenderWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TCPSenderWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TCPSenderWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TCPSenderWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TCPSenderWindow().setVisible(true);
            }
        });
        // Create a new Server Socket for the receiver to connect to.
        // It listens for a new socket connection and accepts it when a
        // receiver wants to connect.
        // Once the receiver has connected, confirmation is printed to the
        // terminal and a data output stream is created for the new socket
        // connection.
        try {
            ServerSocket ssock = new ServerSocket(5000);
            socket = ssock.accept();
            System.out.println("Receiver connected");
            os = socket.getOutputStream();
            dos = new DataOutputStream(os);
        } catch (IOException e) {
            e.printStackTrace();
        }
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton chooseFileButton;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
