$(info $(shell echo This project was built with the Apache Netbeans 14 IDE, and therefore cannot be compiled and run from the terminal.))
$(info $(shell echo It must be compiled and run from within the Netbeans IDE.))
$(info $(shell echo Therefore, please refer to the README.md file which contains the instructions on how to install Apache Netbeans 14 if))
$(info $(shell echo you do not already have it, and how to run the program from within the IDE.))